apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  namespace: pvs-teko9 # Replace with your namespace !!CHECK!!
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: nimrot87/chat_app_mem:latest
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
          env:
            - name: REDIS_HOST
              value: redis-service
          ports:
            - containerPort: 3000
